components:
  parameters:
    id:
      name: id
      in: path
      description: unique identifier of the product
      example: "SKU123456"
      required: true
      schema:
        type: string


  schemas:
    ProductRequest:
      type: object
      description: Request to create a product
      properties:
        name:
          type: string
          description: Name of the product
          example: "Laptop"
        description:
          type: string
          description: Description of the product
          example: "High performance laptop with 16GB RAM and 512GB SSD"
        price:
          type: number
          format: double
          description: Price of the product
        internalCode:
          type: string
          description: Internal code of the product
          example: "INT123456"
        brand:
          type: string
          description: Brand of the product
          example: "BrandName"
        color:
          type: string
          description: Color of the product
          example: "Black"
        productType:
          $ref: '#/components/schemas/ProductType'
          description: Product type CLOTHING,SHOE,PERFUMERY,LINGERIE,HOME
          example: 'COMPUTER'
      additionalProperties: false
      required:
        - name
        - description
        - price
        - internalCode
        - brand
        - color
        - productType

    ProductUpdateRequest:
      type: object
      description: Request to create a product
      properties:
        name:
          type: string
          description: Name of the product
          example: "Laptop"
        description:
          type: string
          description: Description of the product
          example: "High performance laptop with 16GB RAM and 512GB SSD"
        price:
          type: number
          format: double
          description: Price of the product
        color:
          type: string
          description: Color of the product
          example: "Black"
      additionalProperties: false

    Product:
      type: object
      description: Response product data
      properties:
        sku:
          type: string
          description: unique identifier of the product
          example: "SKU123456"
        name:
          type: string
          description: Name of the product
          example: "Laptop"
        description:
          type: string
          description: Description of the product
          example: "High performance laptop with 16GB RAM and 512GB SSD"
        price:
          type: number
          format: double
          description: Price of the product
        brand:
          type: string
          description: Brand of the product
          example: "BrandName"
        color:
          type: string
          description: Color of the product
          example: "Black"
        productType:
          $ref: '#/components/schemas/ProductType'
          description: Product type CLOTHING,SHOE,PERFUMERY,LINGERIE,HOME
          example: 'COMPUTER'
      additionalProperties: false
      required:
        - sku
        - name
        - description
        - price
        - internalCode
        - brand
        - color
        - productType

    ProductType:
      enum:
        - COMPUTER
        - MOBILE
        - COMPONENT
        - PERIPHERAL