noParameter:
  get:
    summary: Return all products
    description: Get a list of products
    operationId: findProducts
    tags:
      - Products
    responses:
      '200':
        description: Products found
        content:
          application/json:
            schema:
                type: array
                maxItems: 500
                items:
                  $ref: '../product/product-components.yml#/components/schemas/Product'
      '401':
        description: Unauthorized
      '404':
        description: Products not found
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      "400":
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      "500":
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'

  post:
    summary: Create a new product
    description: Create a new product with the provided details
    operationId: createProduct
    tags:
        - Products
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../product/product-components.yml#/components/schemas/ProductRequest'
    responses:
      '201':
        description: Product created successfully
        content:
          application/json:
            schema:
              $ref: '../product/product-components.yml#/components/schemas/Product'
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      '401':
        description: Unauthorized
      '409':
        description: Conflict, product already exists
        content:
          application/json:
            schema:
                $ref: '../common.yml#/components/schemas/ErrorResponse'
      '500':
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'

withParameter:
  get:
    summary: Return a products by SKU
    description: Get a product by its unique identifier
    operationId: findProduct
    tags:
      - Products
    parameters:
      - $ref: '../product/product-components.yml#/components/parameters/id'
    responses:
      '200':
        description: Products found
        content:
          application/json:
            schema:
              $ref: '../product/product-components.yml#/components/schemas/Product'
      '401':
        description: Unauthorized
      '404':
        description: Products not found
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      "400":
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      "500":
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'

  delete:
    summary: Delete a product by SKU
    description: Delete a product using its unique identifier
    operationId: deleteProduct
    tags:
      - Products
    parameters:
      - $ref: '../product/product-components.yml#/components/parameters/id'
    responses:
      '204':
        description: Product deleted successfully
      '401':
        description: Unauthorized
      '404':
        description: Product not found
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      '500':
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'

  put:
    summary: Update an existing product
    description: Update the details of an existing product
    operationId: updateProduct
    tags:
      - Products
    parameters:
      - $ref: '../product/product-components.yml#/components/parameters/id'
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../product/product-components.yml#/components/schemas/ProductUpdateRequest'
    responses:
      '200':
        description: Product updated successfully
        content:
          application/json:
            schema:
              $ref: '../product/product-components.yml#/components/schemas/Product'
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      '401':
        description: Unauthorized
      '404':
        description: Product not found
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      '500':
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'

  patch:
    summary: Partially update a product
    description: Update specific fields of an existing product
    operationId: patchProduct
    tags:
      - Products
    parameters:
      - $ref: '../product/product-components.yml#/components/parameters/id'
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../product/product-components.yml#/components/schemas/ProductUpdateRequest'
    responses:
      '200':
        description: Product partially updated successfully
        content:
          application/json:
            schema:
              $ref: '../product/product-components.yml#/components/schemas/Product'
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      '401':
        description: Unauthorized
      '404':
        description: Product not found
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'
      '500':
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: '../common.yml#/components/schemas/ErrorResponse'